# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StJUFoFA5QTge8Ar05I1F15Ds_L2AZWR
"""

import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import Tuple


@dataclass
class FinProperties:
    """Material and geometric properties of the rocket fin."""
    length: float          # Fin span (root to tip) [m]
    chord: float           # Average chord length [m]
    thickness: float       # Fin thickness [m]
    density: float         # Material density [kg/m³]
    elastic_modulus: float # Young's modulus [Pa]

    @property
    def area(self) -> float:
        """Cross-sectional area [m²]."""
        return self.chord * self.thickness

    @property
    def second_moment(self) -> float:
        """Second moment of area for bending about chord axis [m⁴]."""
        return (self.chord * self.thickness**3) / 12

    @property
    def mass_per_length(self) -> float:
        """Linear mass density [kg/m]."""
        return self.density * self.area


def cantilever_eigenvalues(n_modes: int = 5) -> np.ndarray:
    """
    Solve the characteristic equation for cantilever beam eigenvalues.

    The equation is: cos(βL) * cosh(βL) + 1 = 0

    Returns the first n_modes values of βL.
    """
    from scipy.optimize import brentq

    def characteristic_eq(beta_L: float) -> float:
        return np.cos(beta_L) * np.cosh(beta_L) + 1

    eigenvalues = []
    # Search intervals where roots exist (between asymptotes of cos)
    search_starts = [(1.5 + i * np.pi) for i in range(n_modes)]

    for start in search_starts:
        try:
            root = brentq(characteristic_eq, start, start + np.pi - 0.1)
            eigenvalues.append(root)
        except ValueError:
            continue

    return np.array(eigenvalues[:n_modes])


def natural_frequencies(fin: FinProperties, n_modes: int = 5) -> np.ndarray:
    """
    Calculate natural frequencies of bending vibration.

    For a cantilever beam:
    ω_n = (β_n * L)² * sqrt(EI / (ρA * L⁴))

    Returns frequencies in Hz.
    """
    beta_L = cantilever_eigenvalues(n_modes)

    EI = fin.elastic_modulus * fin.second_moment
    rhoA = fin.mass_per_length
    L = fin.length

    omega = (beta_L**2) * np.sqrt(EI / (rhoA * L**4))
    frequencies_hz = omega / (2 * np.pi)

    return frequencies_hz


def mode_shape(x: np.ndarray, beta_L: float, L: float) -> np.ndarray:
    """
    Calculate the normalized mode shape for cantilever bending.

    φ(x) = cosh(βx) - cos(βx) - σ[sinh(βx) - sin(βx)]

    where σ = (cosh(βL) + cos(βL)) / (sinh(βL) + sin(βL))
    """
    beta = beta_L / L

    sigma = (np.cosh(beta_L) + np.cos(beta_L)) / (np.sinh(beta_L) + np.sin(beta_L))

    phi = (np.cosh(beta * x) - np.cos(beta * x)
           - sigma * (np.sinh(beta * x) - np.sin(beta * x)))

    # Normalize so max displacement = 1
    return phi / np.max(np.abs(phi))


def forced_response(
    fin: FinProperties,
    force_amplitude: float,
    force_frequency: float,
    force_location: float,
    damping_ratio: float = 0.02,
    n_modes: int = 5
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Calculate steady-state forced vibration response using modal superposition.

    Args:
        fin: Fin properties
        force_amplitude: Peak force [N]
        force_frequency: Excitation frequency [Hz]
        force_location: Distance from root where force is applied [m]
        damping_ratio: Modal damping ratio (typical: 0.01-0.05)
        n_modes: Number of modes to include

    Returns:
        x: Position along fin [m]
        w_amplitude: Displacement amplitude at each position [m]
    """
    x = np.linspace(0, fin.length, 200)
    omega = 2 * np.pi * force_frequency

    freqs = natural_frequencies(fin, n_modes)
    beta_L_values = cantilever_eigenvalues(n_modes)

    w_amplitude = np.zeros_like(x)

    for i, (f_n, beta_L) in enumerate(zip(freqs, beta_L_values)):
        omega_n = 2 * np.pi * f_n

        # Mode shape
        phi = mode_shape(x, beta_L, fin.length)
        phi_force = mode_shape(np.array([force_location]), beta_L, fin.length)[0]

        # Modal mass (for normalized mode shape, approximate)
        modal_mass = fin.mass_per_length * fin.length * 0.25  # Approximate

        # Frequency response function (magnitude)
        r = omega / omega_n
        H = 1 / np.sqrt((1 - r**2)**2 + (2 * damping_ratio * r)**2)

        # Modal contribution
        w_amplitude += (force_amplitude * phi_force * phi * H) / (modal_mass * omega_n**2)

    return x, np.abs(w_amplitude)


def transient_response(
    fin: FinProperties,
    initial_tip_displacement: float,
    damping_ratio: float = 0.02,
    t_max: float = 0.5,
    n_modes: int = 3
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Calculate transient free vibration from initial displacement.

    Returns time history of tip displacement.
    """
    dt = 1e-5
    t = np.arange(0, t_max, dt)

    freqs = natural_frequencies(fin, n_modes)
    beta_L_values = cantilever_eigenvalues(n_modes)

    # Get mode shapes at tip
    phi_tip = np.array([mode_shape(np.array([fin.length]), bl, fin.length)[0]
                        for bl in beta_L_values])

    # Initial modal coordinates (simplified - assumes first mode dominates)
    q0 = np.zeros(n_modes)
    q0[0] = initial_tip_displacement / phi_tip[0]

    w_tip = np.zeros_like(t)

    for i, (f_n, phi_t) in enumerate(zip(freqs, phi_tip)):
        omega_n = 2 * np.pi * f_n
        omega_d = omega_n * np.sqrt(1 - damping_ratio**2)  # Damped frequency

        # Free vibration response
        w_tip += (q0[i] * phi_t * np.exp(-damping_ratio * omega_n * t)
                  * np.cos(omega_d * t))

    return t, w_tip


def plot_analysis(fin: FinProperties):
    """Generate comprehensive visualization of fin vibration characteristics."""
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))

    # 1. Mode shapes
    ax1 = axes[0, 0]
    x = np.linspace(0, fin.length, 200)
    beta_L_values = cantilever_eigenvalues(5)
    freqs = natural_frequencies(fin, 5)

    for i, (beta_L, f) in enumerate(zip(beta_L_values, freqs)):
        phi = mode_shape(x, beta_L, fin.length)
        ax1.plot(x * 1000, phi, label=f'Mode {i+1}: {f:.1f} Hz', linewidth=2)

    ax1.set_xlabel('Position along fin (mm)')
    ax1.set_ylabel('Normalized displacement')
    ax1.set_title('Bending Mode Shapes')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.axhline(y=0, color='k', linewidth=0.5)

    # 2. Frequency response
    ax2 = axes[0, 1]
    freq_range = np.linspace(1, freqs[2] * 1.5, 500)

    for zeta in [0.01, 0.02, 0.05]:
        response = []
        for f in freq_range:
            _, w = forced_response(fin, 1.0, f, fin.length, zeta, n_modes=3)
            response.append(np.max(w))
        ax2.semilogy(freq_range, response, label=f'ζ = {zeta}', linewidth=2)

    for f in freqs[:3]:
        ax2.axvline(x=f, color='gray', linestyle='--', alpha=0.5)

    ax2.set_xlabel('Excitation frequency (Hz)')
    ax2.set_ylabel('Tip displacement amplitude (m/N)')
    ax2.set_title('Frequency Response Function')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Transient response
    ax3 = axes[1, 0]
    t, w = transient_response(fin, 0.001, damping_ratio=0.02, t_max=0.3)
    ax3.plot(t * 1000, w * 1000, 'b-', linewidth=1)
    ax3.set_xlabel('Time (ms)')
    ax3.set_ylabel('Tip displacement (mm)')
    ax3.set_title('Free Vibration Decay (1 mm initial displacement)')
    ax3.grid(True, alpha=0.3)

    # 4. Natural frequencies bar chart
    ax4 = axes[1, 1]
    modes = range(1, 6)
    ax4.bar(modes, freqs, color='steelblue', edgecolor='navy')
    ax4.set_xlabel('Mode number')
    ax4.set_ylabel('Natural frequency (Hz)')
    ax4.set_title('Natural Frequencies')
    ax4.grid(True, alpha=0.3, axis='y')

    for i, f in enumerate(freqs):
        ax4.text(i + 1, f + freqs[0] * 0.05, f'{f:.1f}', ha='center', fontsize=9)

    plt.tight_layout()
    plt.savefig('fin_vibration_analysis.png', dpi=150, bbox_inches='tight')
    plt.show()


# Example usage
if __name__ == "__main__":
    # Typical rocket fin (aluminum)
    fin = FinProperties(
        length=0.15,           # 150 mm span
        chord=0.08,            # 80 mm chord
        thickness=0.003,       # 3 mm thick
        density=2700,          # Aluminum
        elastic_modulus=70e9   # 70 GPa
    )

    print("=" * 50)
    print("ROCKET FIN BENDING VIBRATION ANALYSIS")
    print("=" * 50)
    print(f"\nFin Properties:")
    print(f"  Length:          {fin.length * 1000:.1f} mm")
    print(f"  Chord:           {fin.chord * 1000:.1f} mm")
    print(f"  Thickness:       {fin.thickness * 1000:.1f} mm")
    print(f"  Material:        Aluminum (ρ = {fin.density} kg/m³, E = {fin.elastic_modulus/1e9:.0f} GPa)")
    print(f"  Second moment I: {fin.second_moment:.3e} m⁴")
    print(f"  Mass per length: {fin.mass_per_length:.3f} kg/m")

    # Calculate natural frequencies
    freqs = natural_frequencies(fin, n_modes=5)
    print(f"\nNatural Frequencies (Bending):")
    for i, f in enumerate(freqs):
        print(f"  Mode {i+1}: {f:8.2f} Hz  ({f*60:.0f} CPM)")

    # Forced response at specific frequency
    test_freq = freqs[0] * 0.9  # Near first resonance
    x, w = forced_response(fin, force_amplitude=10, force_frequency=test_freq,
                           force_location=fin.length, damping_ratio=0.02)
    print(f"\nForced Response at {test_freq:.1f} Hz (10 N tip load):")
    print(f"  Max tip displacement: {np.max(w)*1000:.3f} mm")

    # Generate plots
    plot_analysis(fin)